[General]
; Key that reloads this file while the game is running.
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ReloadKey=F5

[Regen Per Tick]

Interval=1000

Hp=0
Fp=0
Stamina=0

HpPct=0.5
FpPct=1
StaminaPct=5


[Regen Per Hit]

HpOnHit=0
FpOnHit=0
StaminaOnHit=0

HpPctOnHit=0
FpPctOnHit=0
StaminaPctOnHit=0


[Regen Per Damage]

HpOnDamage=0
FpOnDamage=0
StaminaOnDamage=0


[Debug]

DebugLog=false
