[General]
; Key that reloads this file while the game is running.
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ReloadKey=F5

[Damage Multipliers]
; Base damage (physical/magic/fire/thunder/dark), per weapon type.
; Bow/Greatbow
Bow.DamageMultiplier=1.5
; Crossbow (weaponCategory=11, wepType=55)
Crossbow.DamageMultiplier=3
; Ballista (weaponCategory=11, wepType=56)
Ballista.DamageMultiplier=4


[Common]
; Bow/Greatbow only.
Bow.ScalingMultiplier=2
Bow.UnlockAOW=true
Bow.WeightMultiplier=0.5
Bow.SellValueMultiplier=2
; Crossbow
Crossbow.WeightMultiplier=0.5
Crossbow.SellValueMultiplier=2
; Ballista
Ballista.WeightMultiplier=0.5
Ballista.SellValueMultiplier=2


[Bullet Tuning]
Bullet.Arrow.MaxQuantity=255
Bullet.Bolt.MaxQuantity=255
Bullet.SpeedMultiplier=3.5
Bullet.RangeMultiplier=2
Bullet.SpreadMultiplier=2
Bullet.RainOfArrowsCount=6


[Logging]
LogFile=true
