// Generated from `NPC_THINK_PARAM_ST` in fromsoftware-rs (rev 59fbd3b), scalar
// fields only: (snake_case name, byte offset in the row, type). Bit-field bytes
// and padding are left out.

use super::Kind;

pub const ROW_SIZE: usize = 228;

pub const FIELDS: &[(&str, usize, Kind)] = &[
    ("logic_id", 0x4, Kind::I32),
    ("battle_goal_id", 0x8, Kind::I32),
    ("search_eye_dist", 0xc, Kind::U16),
    ("search_eye_ang_y", 0xe, Kind::U8),
    ("sp_effect_id_ranged_attack", 0x10, Kind::I32),
    ("search_target_lv1_forget_time", 0x14, Kind::F32),
    ("search_target_lv2_forget_time", 0x18, Kind::F32),
    ("back_home_life_on_hit_ene_wal", 0x1c, Kind::F32),
    ("sight_target_forget_time", 0x20, Kind::F32),
    ("id_attack_cannot_move", 0x24, Kind::I32),
    ("ear_dist", 0x28, Kind::F32),
    ("call_help_action_anim_id", 0x2c, Kind::I32),
    ("call_help_call_action_id", 0x30, Kind::I32),
    ("eye_dist", 0x34, Kind::U16),
    ("is_guard_act", 0x36, Kind::U8),
    ("ear_soundcut_dist", 0x38, Kind::U16),
    ("nose_dist", 0x3a, Kind::U16),
    ("max_backhome_dist", 0x3c, Kind::U16),
    ("backhome_dist", 0x3e, Kind::U16),
    ("backhome_battle_dist", 0x40, Kind::U16),
    ("non_battle_act_life", 0x42, Kind::U16),
    ("back_home_look_target_time", 0x44, Kind::U16),
    ("back_home_look_target_dist", 0x46, Kind::U16),
    ("sound_target_forget_time", 0x48, Kind::F32),
    ("battle_start_dist", 0x4c, Kind::U16),
    ("call_help_my_peer_id", 0x4e, Kind::U16),
    ("call_help_call_peer_id", 0x50, Kind::U16),
    ("target_sys_dmg_effect_rate", 0x52, Kind::U16),
    ("team_attack_effectivity", 0x54, Kind::U8),
    ("eye_ang_x", 0x55, Kind::U8),
    ("eye_ang_y", 0x56, Kind::U8),
    ("disable_dark", 0x57, Kind::U8),
    ("caravan_role", 0x58, Kind::U8),
    ("call_help_call_valid_min_dist_target", 0x59, Kind::U8),
    ("call_help_call_valid_range", 0x5a, Kind::U8),
    ("call_help_forget_time_by_arrival", 0x5b, Kind::U8),
    ("call_help_min_wait_time", 0x5c, Kind::U8),
    ("call_help_max_wait_time", 0x5d, Kind::U8),
    ("goal_action_to_caution", 0x5e, Kind::U8),
    ("ear_listen_level", 0x5f, Kind::U8),
    ("call_help_reply_behavior_type", 0x60, Kind::U8),
    ("disable_path_move", 0x61, Kind::U8),
    ("skip_arrival_visible_check", 0x62, Kind::U8),
    ("think_attr_do_admirer", 0x63, Kind::U8),
    ("search_threshold_lv0to_lv1", 0x68, Kind::I32),
    ("search_threshold_lv1to_lv2", 0x6c, Kind::I32),
    ("platoon_reply_time", 0x70, Kind::F32),
    ("platoon_reply_add_random_time", 0x74, Kind::F32),
    ("search_eye_ang_x", 0x78, Kind::U8),
    ("is_update_battle_sight", 0x79, Kind::U8),
    ("battle_eye_update_dist", 0x7a, Kind::U16),
    ("battle_eye_update_ang_x", 0x7c, Kind::U8),
    ("battle_eye_update_ang_y", 0x7d, Kind::U8),
    ("eye_back_offset_dist", 0x8e, Kind::U16),
    ("eye_begin_dist", 0x90, Kind::U16),
    ("act_type_on_failed_path", 0x92, Kind::U8),
    ("goal_action_to_caution_important", 0x93, Kind::U8),
    ("shift_anime_id_ranged_attack", 0x94, Kind::I32),
    ("act_type_on_non_btl_failed_path", 0x98, Kind::U8),
    ("is_buddy_ai", 0x99, Kind::U8),
    ("goal_action_to_search_lv1", 0x9a, Kind::U8),
    ("goal_action_to_search_lv2", 0x9b, Kind::U8),
    ("enable_jump_move", 0x9c, Kind::U8),
    ("disable_local_steering", 0x9d, Kind::U8),
    ("goal_action_to_disappear", 0x9e, Kind::U8),
    ("change_state_action_to_normal", 0x9f, Kind::U8),
    ("memory_target_forget_time", 0xa0, Kind::F32),
    ("ranged_attack_id", 0xa4, Kind::I32),
    ("use_fall_on_normal_caution", 0xa8, Kind::U8),
    ("use_fall_on_search_battle", 0xa9, Kind::U8),
    ("enable_jump_move_on_battle", 0xaa, Kind::U8),
    ("back_to_home_stuck_act", 0xab, Kind::U8),
    ("sound_behavior_id01", 0xb0, Kind::I32),
    ("sound_behavior_id02", 0xb4, Kind::I32),
    ("sound_behavior_id03", 0xb8, Kind::I32),
    ("sound_behavior_id04", 0xbc, Kind::I32),
    ("sound_behavior_id05", 0xc0, Kind::I32),
    ("sound_behavior_id06", 0xc4, Kind::I32),
    ("sound_behavior_id07", 0xc8, Kind::I32),
    ("sound_behavior_id08", 0xcc, Kind::I32),
    ("weapon_off_special_effect_id", 0xd0, Kind::I32),
    ("weapon_on_special_effect_id", 0xd4, Kind::I32),
    ("weapon_off_anim_id", 0xd8, Kind::I32),
    ("weapon_on_anim_id", 0xdc, Kind::I32),
    ("surprise_anim_id", 0xe0, Kind::I32),
    ("disable_param_nt", 0x0, Kind::Bit(0)),
    ("is_no_avoid_huge_enemy", 0xf, Kind::Bit(0)),
    ("enable_weapon_on_off", 0xf, Kind::Bit(1)),
    ("target_ai_lock_dmy_poly", 0xf, Kind::Bit(2)),
    ("enable_navi_flg_edge", 0x64, Kind::Bit(0)),
    ("enable_navi_flg_large_space", 0x64, Kind::Bit(1)),
    ("enable_navi_flg_ladder", 0x64, Kind::Bit(2)),
    ("enable_navi_flg_hole", 0x64, Kind::Bit(3)),
    ("enable_navi_flg_door", 0x64, Kind::Bit(4)),
    ("enable_navi_flg_in_side_wall", 0x64, Kind::Bit(5)),
    ("enable_navi_flg_lava", 0x64, Kind::Bit(6)),
    ("enable_navi_flg_edge_ordinary", 0x64, Kind::Bit(7)),
];
