[General]
; Key that reloads this file while the game is running.
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ReloadKey=0x74

; ; Hệ số nhân rune nhận được từ mọi nguồn
; ; Mặt định tăng gấp đôi lượng Rune nhận được từ mọi nguồn
; ; Đặt thành 1 để có giá trị mặt định của trò chơi
; RuneMultiplier=2

; ; Hệ số nhân trọng lượng nhân vật
; ; Mặt định giảm 50% trọng lượng hiện tại của nhân vật
; ; Đặt thành 1 để có giá trị mặt định của trò chơi
; WeightMultiplier=0.5

; ; Hệ số nhân tỉ lệ rơi của nhân vật
; ; Mặt định tăng gấp đôi tỉ lệ rơi hiện tại của nhân vật
; ; Đặt thành 1 để có giá trị mặt định của trò chơi
; DropRateMultiplier=2

; ; Cho phép triệu hồi Torrent ở bất cứ đâu, không bị giới hạn trong các khu vực.
; TorrentAnywhere=true


[Regen Per Tick]
; Bật/tắt tính năng này
Regen.PerTick.Enabled=true

; Các điều kiện kích hoạt
; 0 = Luôn kích hoạt
; 1 = Chỉ kích hoạt khi đang nhàng rỗi, không chiến đấu
; 2 = Chỉ kích hoạt khi đang chiến đấu
Regen.PerTick.Trigger=0

; Tần suất kích hoạt (tính bằng mili giây). Ví dụ: 1000=1 giây, 500=0.5 giây,
; Giá trị càng nhỏ thì càng nhanh, nhưng cũng sẽ tốn tài nguyên hơn.
Regen.PerTick.Interval=1000

; Đơn vị cho các giá trị bên dưới. 0 = điểm, 1 = phần trăm
; 0 = điểm, ví dụ: HP=1 sẽ hồi 1 điểm máu mỗi tick
; 1 = phần trăm, ví dụ: HP=1 sẽ hồi 1% máu tối đa mỗi tick
Regen.PerTick.Unit=1

; Các giá trị hồi phục mỗi tick
Regen.PerTick.HP=0.5
Regen.PerTick.FP=1
Regen.PerTick.Stamina=5


[Regen Per Hit]
; Bật/tắt tính năng này
Regen.PerHit.Enabled=false

; 0 = Hồi phục theo số điểm cố định mỗi khi đánh trúng.
; 1 = Hồi phục theo phần trăm chỉ số của người chơi khi đánh trúng.
; 2 = Hồi phục theo phần trăm sát thương gây ra khi đánh trúng.
; Gợi ý cấu hình:
;   0: HP=7, FP=3, Stamina=5
;   1: Giả sử giữa game với ~1500HP, ~130FP/Stamina
;       HP=2 (~30 Hp/hit), FP=5 (~6.5 Fp/hit) Stamina=5 (~6.5 Stamina/hit).
;   2: Giả sử giữ game với ~ 200 damage/hit
;       HP=10 (~20 Hp/hit), FP=5 (~10 Fp/hit) Stamina=5 (~10 Stamina/hit).
Regen.PerHit.Trigger=0

; Các giá trị hồi phục
Regen.PerHit.HP=0.5
Regen.PerHit.FP=1
Regen.PerHit.Stamina=5


; [Rune Reward]
; ; Bật/tắt tính năng này
; Rune.Passive.Enabled=true

; ; Tần suất kích hoạt (tính bằng mili giây). Ví dụ: 1000=1 giây, 500=0.5 giây,
; Rune.Passive.Interval=10000

; ; Số lượng rune nhận được
; Rune.Passive.Amount=100

; ; Phẩn thưởng các cột mốc quan trọng, định dạng theo (ms:rune)
; ; Mặt định: 30p=5000, 1H=10000, 2H=25000, 
; ; Đặt giá trị về 0 sẽ vô hiệu tính năng này
; Rune.Milestone=1800:5000,3600:10000,7200:25000,10800:40000,21600:100000,43200:500000,86400:1000000


; [Spirit]
; ; Số lượng spirit được triệu hồi mỗi lần, tối đa ở 10
; Spirit.Summon.Amount=0

; ; Hệ số nhân số lượng spirit được triệu hồi, không thể vượt quá 10 spirit bằng cách này
; ; Ví dụ với 3 con sói cô độc, đặt giá trị = 2 sẽ triệu hồi 6 con sói 
; Spirit.Summon.Multiplier=1

; ; Cho phép triệu hồi spirit ở bất cứ đâu
; Spirit.Summon.Anywhere=true

; ; Cho phép spirit có màu sắc tự nhiên thay vì màu trắng linh hồn
; Spirit.Color=true

; ; Cho phép spirit hồi phục mỗi giây, đặt thành 0 sẽ vô hiệu hoá tính năng này
; Spirit.Regen=0.75


[Debug]
; Ghi log cho mục đích debug
DebugLog=false

; Ghi log cho module Regen
RegenLog=true
; Ghi log cho module Rune Reward
; RuneLog=true