[General]
; Key that reloads this file while the game is running.
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
ReloadKey=F5

[Regen Per Tick]

; Tần suất kích hoạt hồi phục theo ms, đặt thành 0 sẽ vô hiệu hoá tính năng này
Regen.Interval=1000

; Số lượng HP/FP/Stamina hồi phục mỗi tick, đặt thành 0 sẽ vô hiệu hoá tính năng này
Regen.Hp=0
Regen.Fp=0
Regen.Stamina=0

; Phần trăm HP/FP/Stamina hồi phục mỗi tick, đặt thành 0 sẽ vô hiệu hoá tính năng này
Regen.HpPct=0.5
Regen.FpPct=1
Regen.StaminaPct=5


[Regen Per Hit]

; Số lượng HP/FP/Stamina hồi phục khi tấn công trúng kẻ địch, đặt thành 0 sẽ vô hiệu hoá tính năng này
Regen.HpOnHit=0
Regen.FpOnHit=0
Regen.StaminaOnHit=0

; Phần trăm HP/FP/Stamina hồi phục khi tấn công trúng kẻ địch, đặt thành 0 sẽ vô hiệu hoá tính năng này
Regen.HpPctOnHit=0
Regen.FpPctOnHit=0
Regen.StaminaPctOnHit=0


[Rune]

; Tần suất kích hoạt nhận rune theo ms (mặt định 10000 = 10 giây), đặt thành 0 sẽ vô hiệu hoá tính năng này
Rune.Interval=10000

; Số lượng rune nhận được mỗi tick, đặt thành 0 sẽ vô hiệu hoá tính năng này
Rune.Amount=50

; Phẩn thưởng nhận được theo giờ chơi (định dạng theo ms:rune), đặt thành 0 sẽ vô hiệu hoá tính năng này
Rune.Bonus=1800:5000,3600:10000,7200:25000,10800:40000,21600:100000,43200:500000,86400:1000000

; Hệ số nhân rune nhận được từ mọi nguồn, đặt thành 1 sẽ không thay đổi, đặt thành âm thay vào đó sẽ trừ đi số rune nhận được, ví dụ -0.5 sẽ trừ đi 50% rune nhận được
Rune.Multiplier=2


[Spirit]

; Số lượng spirit được triệu hồi, giới hạn ở 10, đặt thành 0 sẽ vô hiệu hoá tính năng này
Spirit.Amount=0

; Hệ số nhân số lượng spirit được triệu hồi, đặt thành 1 sẽ không thay đổi, không thể có nhiều hơn 10 spirit được triệu hồi.
Spirit.Multiplier=1

; Cho phép triệu hồi spirit ở bất cứ đâu, không cần đài hồi sinh, kể cả khi đang xâm nhập thế giới NPC, và không giới hạn số lần triệu hồi mỗi đài hồi sinh. Đặt thành false sẽ giữ nguyên luật gốc.
Spirit.SummonAnywhere=true

; Cho phép spirit có màu sắc, đặt thành false sẽ giữ nguyên màu sắc gốc của spirit.
Spirit.Color=true

; Phần trăm hồi phục spirit mỗi tick, đặt thành 0 sẽ vô hiệu hoá tính năng này
Spirit.Regen=0.75


[Misc]
; Điều chỉnh tải trọng nhân vật, đặt thành 1 sẽ không thay đổi,
; Đặt thành 0.5 sẽ giảm tải trọng đi 50%, đặt thành 2 sẽ tăng tải trọng lên gấp đôi
WeightMultiplier=0.5

; Điều chỉnh tỷ lệ rơi vật phẩm, đặt thành 1 sẽ không thay đổi,
; Đặt thành 2 sẽ tăng tỷ lệ rơi vật phẩm lên gấp đôi với chỉ số hiện tại của người chơi
DropRateMultiplier=2

; Cho phép triệu hồi Torrent ở bất cứ đâu, không bị giới hạn trong các khu vực.
TorrentAnywhere=true


[Debug]

; Tạo file log để debug, đặt thành false sẽ vô hiệu hoá tính năng này
DebugLog=false
