[WeightMultiplier]

; Seconds to wait after game launch before applying the mod.
InitialDelaySeconds=5

; Percent to reduce your total equip load by. 0 = no change.
; Example: WeightReductionPercent=50 with a real load of 100 shows as 50.
; Example: WeightReductionPercent=100 with a real load of 100 shows as 0.
; Negative values increase your load instead.
; Example: WeightReductionPercent=-100 with a real load of 100 shows as 200.
WeightReductionPercent=50
